project:
  type: book
  title: "R Intro"
  output-dir: docs

execute:
  cache: true
  eval: false
  freeze: auto

book:
  title: "R Intro"
  author: ""
  chapters:
    - index.qmd
    - part: "Semana 1"
      chapters:
        - 1-intro.qmd
        - 2-sintaxis.qmd
        - 3-data_type.qmd
    - part: "Semana 2"
      chapters:
        - 4-tidyverse.qmd
        - 5-data_str.qmd
        - 6-visualizar.qmd
    - part: "Semana 3"
      chapters:
        - 7-manipular.qmd
    - part: "Semana 4"
      chapters:
        - 8-model_0.qmd
        - 8-model_1.qmd
        - 9-model_2.qmd
    - referencias.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: cosmo
      dark: superhero

